# Builds cmd/burnmon-dev/station/station_atlas.js from Kenney Space Kit 2.0
# (CC0, https://kenney.nl/assets/space-kit). Run from this folder:
#   python build_atlas.py <kit>              the kit's own PNGs (elevation 30, azimuth 45)
#   python build_atlas.py <kit> <renders>    render_iso.py's renders (the Station's view)
#   python build_atlas.py --site <renders> [manifest]   the site theme's atlas:
#     station_atlas_site.js (window.BM_STATION_ATLAS_SITE) from render_site.py's
#     renders of site_manifest.json; refuses a proj that differs from the space atlas's
# The second form also copies <renders>\proj.json (the camera's elevation and
# the deck's tile axes on screen) into the atlas, so station.js projects the
# floor exactly as the sprites were rendered. Needs Pillow. Every sprite is
# cropped to its bounding box; the stored offset is relative to the tile
# centre, so the JS can anchor any sprite on a tile centre. LF on every OS.
import base64, io, json, math, os, re, sys
from PIL import Image

SITE = sys.argv[1:2] == ['--site']
if SITE:
    del sys.argv[1]
    MANIFEST = sys.argv[2] if len(sys.argv) > 2 else 'site_manifest.json'
KIT = sys.argv[1] if len(sys.argv) > 1 else 'kenney_space-kit'
RENDERS = sys.argv[1] if SITE else (sys.argv[2] if len(sys.argv) > 2 else None)
VIEW = {'elev': 30, 'proj': [65, -65, 32.5, 32.5]}
if RENDERS:
    VIEW = json.load(open(os.path.join(RENDERS, 'proj.json')))
ELEV = float(VIEW['elev'])
STATION = os.path.join('..', '..', 'cmd', 'burnmon-dev', 'station')
OUT = os.path.join(STATION, 'station_atlas_site.js' if SITE else 'station_atlas.js')
D4 = ['NE', 'NW', 'SE', 'SW']
D8 = ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW']
names = []
def add(base, dirs):
    names.extend(base + '_' + d for d in dirs)
add('corridor_wall', D4); add('corridor_wallCorner', D4)
add('gate_complex', D4); add('gate_simple', D4)
add('desk_computer', D4); add('desk_computerScreen', D4); add('desk_computerCorner', D4)
add('desk_chair', D4); add('desk_chairArms', D4); add('desk_chairStool', ['SE'])
add('structure_closed', ['SE']); add('structure_detailed', ['SE']); add('structure', ['SE'])
add('satelliteDish_large', ['SE', 'SW']); add('satelliteDish', ['SE', 'SW']); add('satelliteDish_detailed', ['SE', 'SW'])
add('machine_wireless', ['SE', 'SW']); add('machine_wirelessCable', ['SE', 'SW'])
add('platform_low', ['SE']); add('platform_small', ['SE']); add('platform_center', ['SE'])
add('machine_generator', ['SE', 'SW']); add('machine_generatorLarge', ['SE', 'SW'])
add('machine_barrel', ['SE', 'SW']); add('machine_barrelLarge', ['SE', 'SW'])
add('barrels', ['SE']); add('barrel', ['SE']); add('pipe_ringSupport', ['SE', 'SW'])
add('rail', D4); add('rail_middle', ['SE', 'SW']); add('supports_low', ['SE']); add('rover', D4)
for a in ['astronautA', 'astronautB', 'alien']:
    add(a, D8)
if SITE:
    names = []
    for base, spec in json.load(open(MANIFEST, encoding='utf-8'))['entries'].items():
        for d in spec['dirs']:
            names.extend(base + '_' + d + ('_' + str(i) if spec.get('frames') else '') for i in range(len(spec.get('frames') or [0])))
    space = open(os.path.join(STATION, 'station_atlas.js'), encoding='utf-8').read()
    if json.loads(re.search(r'proj: (\[[^\]]*\])', space).group(1)) != VIEW['proj']:
        sys.exit('proj differs from station_atlas.js: ' + str(VIEW['proj']) + ' (render with BMS_AZIMUTH=30, elevation 30)')

# The tile centre in a 512 px render: the kit's (256, 311.5) at elevation
# 30, render_iso.py's anchor_y otherwise.
AX, AY = 256, 256 + (311.5 - 256) * math.cos(math.radians(ELEV)) / math.cos(math.radians(30))
items = []
for n in names:
    src = os.path.join(RENDERS, n + '.png') if RENDERS else os.path.join(KIT, 'Isometric', n + '.png')
    im = Image.open(src).convert('RGBA')
    bb = im.getbbox()
    items.append((n, im.crop(bb), bb[0] - AX, bb[1] - AY))
items.sort(key=lambda t: -t[1].size[1])
W = 1024; x = y = sh = 0; pos = {}
for n, im, ox, oy in items:
    w, h = im.size
    if x + w > W:
        x = 0; y += sh + 1; sh = 0
    pos[n] = (x, y, w, h, ox, oy); x += w + 1; sh = max(sh, h)
A = Image.new('RGBA', (W, y + sh))
for n, im, ox, oy in items:
    A.paste(im, pos[n][:2])
q = A.quantize(colors=256, method=Image.Quantize.FASTOCTREE)
buf = io.BytesIO(); q.save(buf, format='PNG', optimize=True)
b64 = base64.b64encode(buf.getvalue()).decode()
CREDIT = ("from Kenney City Kit (Industrial) 2.0, Factory Kit 3.0, Building Kit and Car Kit (CC0, www.kenney.nl),\n"
          "// Quaternius Worker (CC0, Ultimate Modular Men, via poly.pizza) and an OpenGameArt excavator (CC0),\n"
          "// plus props built in site_proc.py; see tools/station_atlas/CREDITS.txt" if SITE
          else "from Kenney Space Kit 2.0 (CC0, www.kenney.nl)")
js = ("// Generated by tools/station_atlas/build_atlas.py " + CREDIT + ".\n"
      "// Do not edit by hand. Each entry: [x, y, w, h, ox, oy], ox/oy relative to the tile centre at 1x.\n"
      "// elev: the camera's elevation in degrees. proj: the deck's tile axes on screen at 1x,\n"
      "// [x to sx, y to sx, x to sy, y to sy], as the sprites were rendered.\n"
      "window.BM_STATION_ATLAS" + ('_SITE' if SITE else '') + " = {\n  elev: " + ('%g' % ELEV) + ",\n  proj: " + json.dumps(VIEW['proj']) + ",\n  png: 'data:image/png;base64," + b64 + "',\n  map: "
      + json.dumps(pos, separators=(',', ':')) + "\n};\n")
open(OUT, 'w', newline='\n').write(js)
print(len(names), 'sprites,', len(js), 'bytes ->', OUT)
